### ISSUE TITLE
Bower Search ate my Windows 8.1 machine!

### ISSUE THREAD

**Issue by ewlloyd** [khornberg/brackets-cardboard#10]
Just tried to run a Bower search (search term "bootstrap"), and my machine locked up, frozen mouse and all. After doing a hard reset (the only option available to me), I tried it again with Process Explorer on the other monitor, and discovered that Brackets was launching a metric $#!+load of cmd.exe and node.exe processes. I was able to kill the process tree before my box became unusable again, but only just.

The folder I had open in the Brackets instance was completely empty, if that helps at all. Let me know if there's anything I can do to help figure this out.

**Comment by khornberg** [comment]
@ewlloyd if you still care, can you try this now?
